AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Document Extraction

  SAM Template for Konze

Globals:
  Function:
    Runtime: python3.10
    Handler: main.lambda_handler
    Architectures:
      - x86_64
    Tracing: Active
    Environment:
      Variables:
        LOG_LEVEL: INFO

Resources:    
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
        AllowMethods: "'*'"

  KonzeExtractionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Konze_Extraction/
      Timeout: 580
      MemorySize: 2048
      Policies:
        - Statement:
            - Sid: "FullAccessToS3Bucket"
              Effect: "Allow"
              Action:
                - "s3:*"
              Resource:
                - "arn:aws:s3:::chartmate-idp"
                - "arn:aws:s3:::chartmate-idp/*"
        # - Statement:
        #     - Sid: "InvokeRequestApiFunction"
        #       Effect: "Allow"
        #       Action: "lambda:InvokeFunction"
        #       Resource: !GetAtt ChartmateFunction.Arn
        - Statement:
            - Sid: "BedrockScopedAccess"
              Effect: "Allow"
              Action:
                - "bedrock:InvokeModel"
              Resource:
                - "arn:aws:bedrock:*::foundation-model/*"
        - Statement:
            - Sid: "SSMAccess"
              Effect: "Allow"
              Action:
                - "ssm:GetParameter"
                - "ssm:GetParameters"
                - "ssm:GetParametersByPath" # Add other SSM actions as needed
                - "ssm:PutParameter"
              Resource: "*"

  KonzeEmbeddingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Konze_Embeddings/
      Timeout: 480
      MemorySize: 2048
      Policies:
        - Statement:
            - Sid: "FullAccessToS3Bucket"
              Effect: "Allow"
              Action:
                - "s3:*"
              Resource:
                - "arn:aws:s3:::chartmate-idp"
                - "arn:aws:s3:::chartmate-idp/*"
        - Statement:
            - Sid: "InvokeRequestApiFunction"
              Effect: "Allow"
              Action: "lambda:InvokeFunction"
              Resource: !GetAtt KonzeExtractionFunction.Arn
        - Statement:
            - Sid: "BedrockScopedAccess"
              Effect: "Allow"
              Action:
                - "bedrock:InvokeModel"
              Resource:
                - "arn:aws:bedrock:*::foundation-model/*"
        - Statement:
            - Sid: "FullAccessToTextract"
              Effect: "Allow"
              Action:
                - "textract:*"
              Resource: "*"
        - Statement:
            - Sid: "SSMAccess"
              Effect: "Allow"
              Action:
                - "ssm:GetParameter"
                - "ssm:GetParameters"
                - "ssm:GetParametersByPath" # Add other SSM actions as needed
                - "ssm:PutParameter"
              Resource: "*"
      Environment:
        Variables:
          CHARTMATE_EXTRACTION_FUNCTION_ARN: !GetAtt KonzeExtractionFunction.Arn


  KonzeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Konze/
      Timeout: 480
      MemorySize: 2048
      Policies:
        - Statement:
            - Sid: "FullAccessToS3Bucket"
              Effect: "Allow"
              Action:
                - "s3:*"
              Resource:
                - "arn:aws:s3:::chartmate-idp"
                - "arn:aws:s3:::chartmate-idp/*"
        - Statement:
            - Sid: "InvokeRequestApiFunction"
              Effect: "Allow"
              Action: "lambda:InvokeFunction"
              Resource: !GetAtt KonzeEmbeddingFunction.Arn
        - Statement:
            - Sid: "BedrockScopedAccess"
              Effect: "Allow"
              Action:
                - "bedrock:InvokeModel"
              Resource:
                - "arn:aws:bedrock:*::foundation-model/*"
        - Statement:
            - Sid: "FullAccessToTextract"
              Effect: "Allow"
              Action:
                - "textract:*"
              Resource: "*"
        - Statement:
            - Sid: "SSMAccess"
              Effect: "Allow"
              Action:
                - "ssm:GetParameter"
                - "ssm:GetParameters"
                - "ssm:GetParametersByPath" # Add other SSM actions as needed
                - "ssm:PutParameter"
              Resource: "*"
      Environment:
        Variables:
          CHARTMATE_EMBEDDING_FUNCTION_ARN: !GetAtt KonzeEmbeddingFunction.Arn
      
  RequestApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Request_api/
      Timeout: 480
      MemorySize: 2048
      Policies:
        - Statement:
            - Sid: "InvokeRequestApiFunction"
              Effect: "Allow"
              Action: "lambda:InvokeFunction"
              Resource: !GetAtt KonzeFunction.Arn
              # NUCLEON_FUNCTION_ARN: !GetAtt NucleonFunction.Arn
        - Statement:
            - Sid: "FullAccessToS3Bucket"
              Effect: "Allow"
              Action:
                - "s3:*"
              Resource:
                - "arn:aws:s3:::chartmate-idp/*"
                - "arn:aws:s3:::chartmate-idp/"
        - Statement:
            - Sid: "SSMAccess"
              Effect: "Allow"
              Action:
                - "ssm:GetParameter"
                - "ssm:GetParameters"
                - "ssm:GetParametersByPath" # Add other SSM actions as needed
                - "ssm:PutParameter"
              Resource: "*"
      Environment:
        Variables:
          CHARTMATE_FUNCTION_ARN: !GetAtt KonzeFunction.Arn
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /requestapi
            Method: POST

  ResponseApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Response_api/
      Timeout: 480
      MemorySize: 2048
      Policies:
        - Statement:
            - Sid: "SSMAccess"
              Effect: "Allow"
              Action:
                - "ssm:GetParameter"
                - "ssm:GetParameters"
                - "ssm:GetParametersByPath" # Add other SSM actions as needed
                - "ssm:PutParameter"
              Resource: "*"
            - Sid: "FullAccessToS3Bucket"
              Effect: "Allow"
              Action:
                - "s3:*"
              Resource:
                - "arn:aws:s3:::chartmate-idp/*"
                - "arn:aws:s3:::chartmate-idp/"
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /responseapi
            Method: POST
